const now = new Date();
const daysAgo = (d) => new Date(now.getTime() - d * 86400000).toISOString();

export const demoCourses = [
  {
    _id: "c1",
    organizationId: "org-1",
    title: "Introduction to Programming",
    description: "Learn the basics of programming with hands-on exercises.",
    instructorId: "u1",
    instructorName: "Dr. Sarah Johnson",
    category: "Programming",
    level: "Beginner",
    thumbnail: null,
    status: "Published",
    enrollmentLimit: 100,
    enrolledCount: 45,
    completionRate: 72,
    hasCertificate: true,
    createdAt: daysAgo(60),
  },
  {
    _id: "c2",
    organizationId: "org-1",
    title: "Data Structures & Algorithms",
    description: "Master data structures and algorithmic thinking.",
    instructorId: "u1",
    instructorName: "Dr. Sarah Johnson",
    category: "Computer Science",
    level: "Intermediate",
    thumbnail: null,
    status: "Published",
    enrollmentLimit: 50,
    enrolledCount: 32,
    completionRate: 65,
    hasCertificate: true,
    createdAt: daysAgo(45),
  },
  {
    _id: "c3",
    organizationId: "org-1",
    title: "Web Development Fundamentals",
    description: "Build modern web applications with HTML, CSS, and JavaScript.",
    instructorId: "u2",
    instructorName: "Mike Wilson",
    category: "Web Development",
    level: "Beginner",
    thumbnail: null,
    status: "Draft",
    enrollmentLimit: 80,
    enrolledCount: 0,
    completionRate: 0,
    hasCertificate: false,
    createdAt: daysAgo(7),
  },
];
