const now = new Date().toISOString();
const orgId = "org-1";

export const demoExternalPlatforms = [
  {
    id: "ep-coursera",
    organizationId: orgId,
    name: "Coursera",
    logoUrl: "/img/platforms/coursera.svg",
    baseUrl: "https://www.coursera.org",
    description: "Learn from top universities and companies. Access thousands of courses in tech, business, and more.",
    category: "Higher Education",
    affiliateTag: null,
    affiliateTrackingEnabled: false,
    isActive: true,
    createdAt: now,
  },
  {
    id: "ep-udemy",
    organizationId: orgId,
    name: "Udemy",
    logoUrl: "/img/platforms/udemy.svg",
    baseUrl: "https://www.udemy.com",
    description: "Online courses for every skill. Learn programming, design, marketing, and more at your own pace.",
    category: "Self-Paced Learning",
    affiliateTag: "lms-affiliate-udemy",
    affiliateTrackingEnabled: true,
    isActive: true,
    createdAt: now,
  },
  {
    id: "ep-edx",
    organizationId: orgId,
    name: "edX",
    logoUrl: "/img/platforms/edx.svg",
    baseUrl: "https://www.edx.org",
    description: "Free online courses from MIT, Harvard, and other top universities. Earn certificates and degrees.",
    category: "Higher Education",
    affiliateTag: null,
    affiliateTrackingEnabled: false,
    isActive: true,
    createdAt: now,
  },
  {
    id: "ep-skillshare",
    organizationId: orgId,
    name: "Skillshare",
    logoUrl: "/img/platforms/skillshare.svg",
    baseUrl: "https://www.skillshare.com",
    description: "Creative classes in design, photography, writing, and more. Learn by doing with project-based courses.",
    category: "Creative",
    affiliateTag: "lms-skillshare-ref",
    affiliateTrackingEnabled: true,
    isActive: true,
    createdAt: now,
  },
  {
    id: "ep-linkedin",
    organizationId: orgId,
    name: "LinkedIn Learning",
    logoUrl: "/img/platforms/linkedin.svg",
    baseUrl: "https://www.linkedin.com/learning",
    description: "Professional development courses. Build skills for your career with expert-led video tutorials.",
    category: "Professional",
    affiliateTag: null,
    affiliateTrackingEnabled: false,
    isActive: true,
    createdAt: now,
  },
];

const courseTemplates = {
  coursera: [
    { title: "Machine Learning", category: "Data Science", level: "Intermediate", tags: ["ML", "Python", "AI"] },
    { title: "Data Science Specialization", category: "Data Science", level: "Beginner", tags: ["R", "Statistics"] },
    { title: "Google UX Design", category: "Design", level: "Beginner", tags: ["UX", "Figma"] },
    { title: "IBM Data Analyst", category: "Data Science", level: "Intermediate", tags: ["Excel", "Python"] },
    { title: "Meta Front-End Developer", category: "Web Development", level: "Beginner", tags: ["HTML", "CSS", "React"] },
    { title: "Python for Everybody", category: "Programming", level: "Beginner", tags: ["Python"] },
    { title: "Financial Markets", category: "Business", level: "Intermediate", tags: ["Finance"] },
    { title: "Introduction to Artificial Intelligence", category: "AI", level: "Beginner", tags: ["AI", "ML"] },
    { title: "Blockchain Basics", category: "Technology", level: "Beginner", tags: ["Blockchain"] },
    { title: "Digital Marketing", category: "Marketing", level: "Beginner", tags: ["Marketing", "SEO"] },
  ],
  udemy: [
    { title: "The Complete Web Developer Bootcamp", category: "Web Development", level: "Beginner", tags: ["HTML", "CSS", "JavaScript"] },
    { title: "Python for Data Science and ML", category: "Data Science", level: "Intermediate", tags: ["Python", "ML"] },
    { title: "React - The Complete Guide", category: "Web Development", level: "Intermediate", tags: ["React"] },
    { title: "AWS Certified Solutions Architect", category: "Cloud", level: "Advanced", tags: ["AWS"] },
    { title: "iOS & Swift - The Complete Guide", category: "Mobile", level: "Beginner", tags: ["Swift", "iOS"] },
    { title: "Adobe Photoshop Masterclass", category: "Design", level: "Beginner", tags: ["Photoshop"] },
    { title: "Excel from Beginner to Advanced", category: "Business", level: "Beginner", tags: ["Excel"] },
    { title: "Node.js - The Complete Guide", category: "Web Development", level: "Intermediate", tags: ["Node.js"] },
    { title: "Docker & Kubernetes", category: "DevOps", level: "Intermediate", tags: ["Docker", "K8s"] },
    { title: "SQL for Data Analysis", category: "Data Science", level: "Beginner", tags: ["SQL"] },
  ],
  edx: [
    { title: "CS50's Introduction to Computer Science", category: "Programming", level: "Beginner", tags: ["C", "Python"] },
    { title: "Data Science: R Basics", category: "Data Science", level: "Beginner", tags: ["R"] },
    { title: "Introduction to Artificial Intelligence", category: "AI", level: "Intermediate", tags: ["AI"] },
    { title: "MicroMasters in Business Analytics", category: "Business", level: "Advanced", tags: ["Analytics"] },
    { title: "Cybersecurity Fundamentals", category: "Security", level: "Beginner", tags: ["Security"] },
    { title: "Supply Chain Management", category: "Business", level: "Intermediate", tags: ["Supply Chain"] },
    { title: "Introduction to Python", category: "Programming", level: "Beginner", tags: ["Python"] },
    { title: "Machine Learning with Python", category: "Data Science", level: "Intermediate", tags: ["ML", "Python"] },
    { title: "Project Management", category: "Business", level: "Beginner", tags: ["PM"] },
    { title: "Introduction to Cloud Computing", category: "Cloud", level: "Beginner", tags: ["Cloud"] },
  ],
  skillshare: [
    { title: "Logo Design in Adobe Illustrator", category: "Design", level: "Beginner", tags: ["Illustrator"] },
    { title: "Photography Masterclass", category: "Photography", level: "Beginner", tags: ["Photography"] },
    { title: "Hand Lettering for Beginners", category: "Design", level: "Beginner", tags: ["Lettering"] },
    { title: "Video Editing in Premiere Pro", category: "Video", level: "Intermediate", tags: ["Premiere"] },
    { title: "UI/UX Design in Figma", category: "Design", level: "Beginner", tags: ["Figma", "UX"] },
    { title: "Social Media Marketing", category: "Marketing", level: "Beginner", tags: ["Social Media"] },
    { title: "Watercolor Painting", category: "Art", level: "Beginner", tags: ["Watercolor"] },
    { title: "Motion Graphics in After Effects", category: "Video", level: "Intermediate", tags: ["After Effects"] },
    { title: "Product Photography", category: "Photography", level: "Beginner", tags: ["Photography"] },
    { title: "Brand Identity Design", category: "Design", level: "Intermediate", tags: ["Branding"] },
  ],
  linkedin: [
    { title: "Excel Essential Training", category: "Business", level: "Beginner", tags: ["Excel"] },
    { title: "Project Management Foundations", category: "Business", level: "Beginner", tags: ["PM"] },
    { title: "Leadership Foundations", category: "Leadership", level: "Intermediate", tags: ["Leadership"] },
    { title: "Communication Foundations", category: "Soft Skills", level: "Beginner", tags: ["Communication"] },
    { title: "Python for Data Science", category: "Data Science", level: "Intermediate", tags: ["Python"] },
    { title: "Power BI Essential Training", category: "Business Intelligence", level: "Beginner", tags: ["Power BI"] },
    { title: "Agile Development", category: "Software", level: "Intermediate", tags: ["Agile"] },
    { title: "Time Management", category: "Productivity", level: "Beginner", tags: ["Productivity"] },
    { title: "Public Speaking", category: "Soft Skills", level: "Beginner", tags: ["Public Speaking"] },
    { title: "Critical Thinking", category: "Soft Skills", level: "Beginner", tags: ["Critical Thinking"] },
  ],
};

const platformIds = {
  coursera: "ep-coursera",
  udemy: "ep-udemy",
  edx: "ep-edx",
  skillshare: "ep-skillshare",
  linkedin: "ep-linkedin",
};

const baseUrls = {
  coursera: "https://www.coursera.org/courses",
  udemy: "https://www.udemy.com/course",
  edx: "https://www.edx.org/learn",
  skillshare: "https://www.skillshare.com",
  linkedin: "https://www.linkedin.com/learning",
};

export const demoExternalCourses = Object.entries(courseTemplates).flatMap(([platformKey, courses]) =>
  courses.map((c, i) => ({
    id: `ec-${platformKey}-${i + 1}`,
    organizationId: orgId,
    platformId: platformIds[platformKey],
    title: c.title,
    description: `${c.title} - Learn from experts on ${platformKey.charAt(0).toUpperCase() + platformKey.slice(1)}.`,
    category: c.category,
    level: c.level,
    thumbnail: null,
    externalUrl: `${baseUrls[platformKey]}/${c.title.toLowerCase().replace(/\s+/g, "-")}`,
    tags: c.tags,
    isFeatured: i < 2,
    createdAt: now,
  }))
);

export const demoExternalClickLogs = [];
