export const demoQuestions = [
  { _id: "q1", examId: "e1", type: "MCQ", questionText: "What is a variable?", options: [{ id: "o1", text: "A storage location" }, { id: "o2", text: "A function" }, { id: "o3", text: "A loop" }], correctAnswer: "o1", marks: 10 },
  { _id: "q2", examId: "e1", type: "MCQ", questionText: "Which keyword declares a constant?", options: [{ id: "o4", text: "var" }, { id: "o5", text: "const" }, { id: "o6", text: "let" }], correctAnswer: "o5", marks: 10 },
  { _id: "q3", examId: "e1", type: "TrueFalse", questionText: "A loop repeats code until a condition is met.", options: [{ id: "o7", text: "True" }, { id: "o8", text: "False" }], correctAnswer: "o7", marks: 10 },
  { _id: "q4", examId: "e1", type: "MCQ", questionText: "What does an array store?", options: [{ id: "o9", text: "Multiple values" }, { id: "o10", text: "Single value" }, { id: "o11", text: "Nothing" }], correctAnswer: "o9", marks: 10 },
  { _id: "q5", examId: "e1", type: "ShortAnswer", questionText: "Name one type of loop.", options: [], correctAnswer: "for", marks: 10 },
  { _id: "q6", examId: "e1", type: "MCQ", questionText: "What is a function?", options: [{ id: "o12", text: "Reusable block of code" }, { id: "o13", text: "A variable" }, { id: "o14", text: "A comment" }], correctAnswer: "o12", marks: 10 },
  { _id: "q7", examId: "e1", type: "TrueFalse", questionText: "JavaScript is a compiled language.", options: [{ id: "o15", text: "True" }, { id: "o16", text: "False" }], correctAnswer: "o16", marks: 10 },
  { _id: "q8", examId: "e1", type: "MCQ", questionText: "Which operator checks equality?", options: [{ id: "o17", text: "=" }, { id: "o18", text: "==" }, { id: "o19", text: ":" }], correctAnswer: "o18", marks: 10 },
  { _id: "q9", examId: "e1", type: "MCQ", questionText: "What does return do in a function?", options: [{ id: "o20", text: "Exits and sends a value back" }, { id: "o21", text: "Starts the function" }, { id: "o22", text: "Prints to console" }], correctAnswer: "o20", marks: 10 },
  { _id: "q10", examId: "e1", type: "TrueFalse", questionText: "An if statement can have an else clause.", options: [{ id: "o23", text: "True" }, { id: "o24", text: "False" }], correctAnswer: "o23", marks: 10 },
  { _id: "q11", examId: "e2", type: "MCQ", questionText: "What is LIFO?", options: [{ id: "o25", text: "Last In First Out" }, { id: "o26", text: "First In First Out" }, { id: "o27", text: "Linear In" }], correctAnswer: "o25", marks: 10 },
  { _id: "q12", examId: "e2", type: "MCQ", questionText: "A stack uses which operations?", options: [{ id: "o28", text: "Push and Pop" }, { id: "o29", text: "Add and Remove" }, { id: "o30", text: "Insert and Delete" }], correctAnswer: "o28", marks: 10 },
  { _id: "q13", examId: "e2", type: "TrueFalse", questionText: "A queue is FIFO.", options: [{ id: "o31", text: "True" }, { id: "o32", text: "False" }], correctAnswer: "o31", marks: 10 },
  { _id: "q14", examId: "e2", type: "MCQ", questionText: "What is the time complexity of array access?", options: [{ id: "o33", text: "O(1)" }, { id: "o34", text: "O(n)" }, { id: "o35", text: "O(log n)" }], correctAnswer: "o33", marks: 10 },
  { _id: "q15", examId: "e2", type: "ShortAnswer", questionText: "Name one linear data structure.", options: [], correctAnswer: "array", marks: 10 },
  { _id: "q16", examId: "e2", type: "MCQ", questionText: "A linked list node contains?", options: [{ id: "o36", text: "Data and pointer" }, { id: "o37", text: "Only data" }, { id: "o38", text: "Only pointer" }], correctAnswer: "o36", marks: 10 },
  { _id: "q17", examId: "e2", type: "TrueFalse", questionText: "Binary search works on unsorted arrays.", options: [{ id: "o39", text: "True" }, { id: "o40", text: "False" }], correctAnswer: "o40", marks: 10 },
  { _id: "q18", examId: "e2", type: "MCQ", questionText: "Which is faster for insertion at end?", options: [{ id: "o41", text: "Dynamic array" }, { id: "o42", text: "Linked list" }, { id: "o43", text: "Same" }], correctAnswer: "o41", marks: 10 },
  { _id: "q19", examId: "e2", type: "MCQ", questionText: "A tree has how many roots?", options: [{ id: "o44", text: "One" }, { id: "o45", text: "Two" }, { id: "o46", text: "Many" }], correctAnswer: "o44", marks: 10 },
  { _id: "q20", examId: "e2", type: "ShortAnswer", questionText: "What does BST stand for?", options: [], correctAnswer: "Binary Search Tree", marks: 10 },
];
