const now = new Date().toISOString();
const orgId = "org-1";

export const demoResearchPlatforms = [
  {
    id: "rp-arxiv",
    organizationId: orgId,
    name: "arXiv",
    logoUrl: "/img/research/arxiv.svg",
    baseUrl: "https://arxiv.org",
    description: "Open-access repository of electronic preprints in physics, mathematics, computer science, and related fields.",
    type: "OpenAccess",
    apiAvailable: true,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "rp-pubmed",
    organizationId: orgId,
    name: "PubMed Central",
    logoUrl: "/img/research/pubmed.svg",
    baseUrl: "https://www.ncbi.nlm.nih.gov/pmc",
    description: "Free full-text archive of biomedical and life sciences journal literature at the U.S. National Institutes of Health.",
    type: "OpenAccess",
    apiAvailable: true,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "rp-doaj",
    organizationId: orgId,
    name: "DOAJ",
    logoUrl: "/img/research/doaj.svg",
    baseUrl: "https://doaj.org",
    description: "Directory of Open Access Journals. Community-curated online directory indexing high-quality, peer-reviewed open access journals.",
    type: "OpenAccess",
    apiAvailable: true,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "rp-core",
    organizationId: orgId,
    name: "CORE",
    logoUrl: "/img/research/core.svg",
    baseUrl: "https://core.ac.uk",
    description: "Aggregator of open access research from repositories and journals worldwide. Largest collection of open access papers.",
    type: "APIIntegrated",
    apiAvailable: true,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "rp-gutenberg",
    organizationId: orgId,
    name: "Project Gutenberg",
    logoUrl: "/img/research/gutenberg.svg",
    baseUrl: "https://www.gutenberg.org",
    description: "Library of over 70,000 free eBooks. Focus on older works for which U.S. copyright has expired.",
    type: "PublicDomain",
    apiAvailable: false,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
];

const resourceTemplates = [
  { platformId: "rp-arxiv", title: "Attention Is All You Need", authors: ["Vaswani et al."], category: "Computer Science", year: 2017, tags: ["transformer", "NLP", "deep learning"] },
  { platformId: "rp-arxiv", title: "BERT: Pre-training of Deep Bidirectional Transformers", authors: ["Devlin et al."], category: "Computer Science", year: 2018, tags: ["NLP", "BERT"] },
  { platformId: "rp-arxiv", title: "ImageNet Classification with Deep CNNs", authors: ["Krizhevsky et al."], category: "Computer Science", year: 2012, tags: ["CNN", "ImageNet"] },
  { platformId: "rp-arxiv", title: "Generative Adversarial Networks", authors: ["Goodfellow et al."], category: "Computer Science", year: 2014, tags: ["GAN", "generative"] },
  { platformId: "rp-pubmed", title: "COVID-19 Vaccine Efficacy and Safety", authors: ["Polack et al."], category: "Medicine", year: 2020, tags: ["vaccine", "COVID-19"] },
  { platformId: "rp-pubmed", title: "CRISPR-Cas9 Gene Editing Applications", authors: ["Doudna, Charpentier"], category: "Biology", year: 2014, tags: ["CRISPR", "gene editing"] },
  { platformId: "rp-pubmed", title: "Microbiome and Human Health", authors: ["Sender et al."], category: "Medicine", year: 2016, tags: ["microbiome", "health"] },
  { platformId: "rp-pubmed", title: "Immunotherapy in Cancer Treatment", authors: ["Ribas, Wolchok"], category: "Oncology", year: 2018, tags: ["immunotherapy", "cancer"] },
  { platformId: "rp-doaj", title: "Open Access Publishing Trends", authors: ["Laakso et al."], category: "Library Science", year: 2011, tags: ["open access", "publishing"] },
  { platformId: "rp-doaj", title: "Sustainable Development Goals in Education", authors: ["Leicht et al."], category: "Education", year: 2018, tags: ["SDG", "education"] },
  { platformId: "rp-core", title: "Machine Learning in Healthcare", authors: ["Esteva et al."], category: "Computer Science", year: 2019, tags: ["ML", "healthcare"] },
  { platformId: "rp-core", title: "Climate Change and Biodiversity", authors: ["Thomas et al."], category: "Environmental Science", year: 2004, tags: ["climate", "biodiversity"] },
  { platformId: "rp-core", title: "Blockchain Technology Survey", authors: ["Zheng et al."], category: "Computer Science", year: 2018, tags: ["blockchain", "survey"] },
  { platformId: "rp-gutenberg", title: "Pride and Prejudice", authors: ["Jane Austen"], category: "Literature", year: 1813, tags: ["fiction", "classic"] },
  { platformId: "rp-gutenberg", title: "Frankenstein", authors: ["Mary Shelley"], category: "Literature", year: 1818, tags: ["fiction", "gothic"] },
  { platformId: "rp-gutenberg", title: "The Adventures of Sherlock Holmes", authors: ["Arthur Conan Doyle"], category: "Literature", year: 1892, tags: ["fiction", "mystery"] },
  { platformId: "rp-gutenberg", title: "A Tale of Two Cities", authors: ["Charles Dickens"], category: "Literature", year: 1859, tags: ["fiction", "historical"] },
  { platformId: "rp-gutenberg", title: "The Art of War", authors: ["Sun Tzu"], category: "Philosophy", year: -500, tags: ["strategy", "philosophy"] },
  { platformId: "rp-arxiv", title: "GPT-3: Language Models are Few-Shot Learners", authors: ["Brown et al."], category: "Computer Science", year: 2020, tags: ["LLM", "GPT"] },
  { platformId: "rp-pubmed", title: "The Human Microbiome Project", authors: ["Turnbaugh et al."], category: "Biology", year: 2007, tags: ["microbiome", "genomics"] },
];

export const demoResearchResources = resourceTemplates.map((r, i) => {
  const platform = demoResearchPlatforms.find((p) => p.id === r.platformId);
  const baseUrl = platform?.baseUrl || "https://example.org";
  const slug = r.title.toLowerCase().replace(/[^a-z0-9]+/g, "-");
  return {
    id: `rr-${i + 1}`,
    organizationId: orgId,
    platformId: r.platformId,
    title: r.title,
    authors: r.authors,
    abstract: `${r.title} - A significant contribution to ${r.category}. Published in ${r.year > 0 ? r.year : "ancient times"}. This open-access resource is available for legal research and citation.`,
    category: r.category,
    publishedYear: r.year > 0 ? r.year : 1813,
    tags: r.tags,
    externalUrl: `${baseUrl}/${slug}`,
    citationFormatAPA: `${r.authors[0]} (${r.year > 0 ? r.year : "n.d."}). ${r.title}. ${platform?.name || "Open Access"}.`,
    citationFormatMLA: `${r.authors[0]}. "${r.title}." ${platform?.name || "Open Access"}, ${r.year > 0 ? r.year : "n.d."}.`,
    isFeatured: i < 6,
    createdAt: now,
  };
});

export const demoResearchBookmarks = [
  { id: "rb-1", userId: "s1", resourceId: "rr-1", savedAt: now },
  { id: "rb-2", userId: "s1", resourceId: "rr-2", savedAt: now },
  { id: "rb-3", userId: "s1", resourceId: "rr-5", savedAt: now },
  { id: "rb-4", userId: "s1", resourceId: "rr-14", savedAt: now },
  { id: "rb-5", userId: "s1", resourceId: "rr-15", savedAt: now },
  { id: "rb-6", userId: "s1", resourceId: "rr-3", savedAt: now },
  { id: "rb-7", userId: "s1", resourceId: "rr-7", savedAt: now },
  { id: "rb-8", userId: "s1", resourceId: "rr-11", savedAt: now },
  { id: "rb-9", userId: "s1", resourceId: "rr-19", savedAt: now },
  { id: "rb-10", userId: "s1", resourceId: "rr-20", savedAt: now },
];

const clickLogBase = [
  { platformId: "rp-arxiv", resourceId: "rr-1" },
  { platformId: "rp-arxiv", resourceId: "rr-1" },
  { platformId: "rp-arxiv", resourceId: "rr-2" },
  { platformId: "rp-arxiv", resourceId: "rr-1" },
  { platformId: "rp-pubmed", resourceId: "rr-5" },
  { platformId: "rp-arxiv", resourceId: "rr-3" },
  { platformId: "rp-gutenberg", resourceId: "rr-14" },
  { platformId: "rp-gutenberg", resourceId: "rr-15" },
  { platformId: "rp-arxiv", resourceId: "rr-1" },
  { platformId: "rp-pubmed", resourceId: "rr-6" },
  { platformId: "rp-core", resourceId: "rr-11" },
  { platformId: "rp-arxiv", resourceId: "rr-2" },
  { platformId: "rp-gutenberg", resourceId: "rr-14" },
  { platformId: "rp-doaj", resourceId: "rr-9" },
  { platformId: "rp-arxiv", resourceId: "rr-19" },
  { platformId: "rp-pubmed", resourceId: "rr-5" },
  { platformId: "rp-arxiv", resourceId: "rr-1" },
  { platformId: "rp-gutenberg", resourceId: "rr-16" },
  { platformId: "rp-core", resourceId: "rr-12" },
  { platformId: "rp-arxiv", resourceId: "rr-4" },
  { platformId: "rp-pubmed", resourceId: "rr-7" },
  { platformId: "rp-arxiv", resourceId: "rr-2" },
  { platformId: "rp-gutenberg", resourceId: "rr-14" },
  { platformId: "rp-doaj", resourceId: "rr-10" },
  { platformId: "rp-arxiv", resourceId: "rr-19" },
  { platformId: "rp-pubmed", resourceId: "rr-20" },
  { platformId: "rp-core", resourceId: "rr-13" },
  { platformId: "rp-gutenberg", resourceId: "rr-15" },
  { platformId: "rp-arxiv", resourceId: "rr-1" },
  { platformId: "rp-pubmed", resourceId: "rr-8" },
];

export const demoResearchClickLogs = clickLogBase.map((c, i) => ({
  id: `rcl-${i + 1}`,
  userId: "s1",
  platformId: c.platformId,
  resourceId: c.resourceId,
  clickedAt: new Date(Date.now() - (i + 1) * 3600000).toISOString(),
}));
